import Sidebar from '@/components/Sidebar'
import './globals.css'
import type { Metadata } from 'next'
// import { Inter } from 'next/font/google'
// const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Amazon Web Scraper',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="flex bg-[#F7FBFF] h-screen">
        {/**sidebar */}
        <Sidebar />
        <main className="p-10 max-w-7xl w-fill mx-auto overflow-y-auto">  
          {/**sidebar */}
         {children}
        </main>
      </body>
    </html>
  )
}
